### ISSUE TITLE
"flight_level" setting just doesn't work at all.

### ISSUE THREAD

**Issue by 0subzero** [FriederHannenheim/Autopilot#2]
**Describe the bug**
Autopilot has no altitude limitation. It can up till 10k easily.

**To Reproduce**
Just use 4040 flight or /flyto command.

**Expected behavior**
It is written in config "Altitude the autopilot flies at. It will slowly rise to the specified y level and then stay there. The default is 350 so the Autopilot won't run into blocks"

**Screenshots**
-

**Comment by FriederHannenheim** [comment]
Does this happen with both fly modes or only 4040?

**Comment by 0subzero** [comment]
I'm not using rocket fly because it is just wasting rockets, sorry, for my opinion.
So don't know if it's working in rocket mode.

**Comment by FriederHannenheim** [comment]
Ok I'll look into it

**Comment by FriederHannenheim** [comment]
This has been fixed on the fabric version of Autopilot. The Forge version is no longer supported.

**Comment by 0subzero** [comment]
Looks like it's working now.
Thanks!
Now the medium speed increased to about 25m/s
