### ISSUE TITLE
Increase flight speed

### ISSUE THREAD

**Issue by 0subzero** [FriederHannenheim/Autopilot#3]
It is "Feature request", not an issue.

By default 4040 flight has the average speed is about 22m/s
You can increase flight speed a bit by flying from high altitude (1000-3000 meters) till 200-300 without 4040 method just set the angle about 20-30 degrees (it is question here about right angle). Speed will be about 40-50 on this part of fly.
So it is not huge speed improvement but better then nothing i believe.

Thanks!

**Comment by FriederHannenheim** [comment]
Has also been implemented in the Fabric version.
